import type {Metadata} from "next";
import "./globals.css";

export const metadata: Metadata = {
    title: "BestForGamers | Steam пополнение",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ru" style={{scrollBehavior: 'smooth'}}>
        <body
            className={`antialiased bg-zinc-950`}
        >
        {children}
        </body>
        </html>
    );
}
